[ALIAS]
GAJAH TUNGGAL = GAJAH TUNGGAL TBK
SPEEDWORK SOLUSI UTAMA = SPEEDWORK SOLUSI UTAMA
SUMBERHARPINDO LESTARISENTOSA = SUMBERHARPINDO LESTARI SENTOSA
SHELL INDONESIA = SHELL INDONESIA
PT SAMA SAMA MITRA MAJU = SAMA SAMA MITRA MAJU
